### ISSUE TITLE
 watch event lost

### ISSUE THREAD

**Issue by Hubery2757** [coreos/jetcd#134]
you can reproduce this bug as such steps:
1. First, add watch for "/test1", then add watch for "/test2", the watch for "/test2" is added later than "/test1"
2. set value for "/test2", you can receive the PUT watch event
3. set value for "/test1", I think we should receive the PUT event, but it's lost

**Comment by fanminshi** [comment]
it should be fixed by https://github.com/coreos/jetcd/pull/123/.

**Comment by Hubery2757** [comment]
I pull the latest code and test it, this bug still be reproduced.

**Comment by Hubery2757** [comment]
I pull the latest code and test it, this bug still be reproduced.

**Comment by fanminshi** [comment]
I am going to change watch interface via https://github.com/coreos/jetcd/pull/98. the new pr reimplements the underly logic. it probably will fix the issue you are having now. In the meantime, let me see what's causing the issue you have.

**Comment by fanminshi** [comment]
@Hubery2757 the #123 fixes the issue you have I just test it out.

```java
@Test
  public void testIssue134() throws ExecutionException, InterruptedException {
    WatchOption option = WatchOption.DEFAULT;
    watcher = watchClient.watch(ByteSequence.fromString("/test1"), option, new Watch.WatchCallback() {

      @Override
      public void onWatch(Header header, List<WatchEvent> events) {
        System.out.println("Event received " + events.get(0).getKeyValue().getKey().toStringUtf8());
      }

      @Override
      public void onResuming() {

      }

    }).get();

    watcher = watchClient.watch(ByteSequence.fromString("/test2"), option, new Watch.WatchCallback() {

      @Override
      public void onWatch(Header header, List<WatchEvent> events) {
        System.out.println("Event received " + events.get(0).getKeyValue().getKey().toStringUtf8());
      }

      @Override
      public void onResuming() {

      }

    }).get();

    kvClient.put(ByteSequence.fromString("/test1"), value);
    kvClient.put(ByteSequence.fromString("/test2"), value);

    Thread.sleep(100);
  }
```
```sh
#output
Event received /test1
Event received /test2
```

**Comment by fanminshi** [comment]
try again with latest master.

**Comment by xiang90** [comment]
try master. i believe this is fixed.
